/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bloodman;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Turbo
 */
public class Admin_interface extends javax.swing.JFrame {

    /**
     * Creates new form Admin_interface
     */
    Database ob = new Database();
    
    String str1 = "Select * from Donor";
    String str2 = "Select * from Record";
    String str3 = "Select * from Feedback";
    DefaultTableModel model1;
    
    public Admin_interface() {
        initComponents();
        this.setLocationRelativeTo(null);
        start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        admin_panel = new javax.swing.JTabbedPane();
        donor_panel = new javax.swing.JPanel();
        adonor_scroll = new javax.swing.JScrollPane();
        adonor_table = new javax.swing.JTable();
        deleteuser_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        adsearch_textfield = new javax.swing.JTextField();
        asearch_button = new javax.swing.JButton();
        adcombo = new javax.swing.JComboBox<String>();
        ddelete_label = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        editd_textfield = new javax.swing.JTextField();
        editm_textfield = new javax.swing.JTextField();
        edity_textfield = new javax.swing.JTextField();
        Dedit_button = new javax.swing.JButton();
        record_panel = new javax.swing.JPanel();
        arecord_scroll = new javax.swing.JScrollPane();
        arecord_table = new javax.swing.JTable();
        deleterecord_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        arecord_textfield = new javax.swing.JTextField();
        arsearch_button = new javax.swing.JButton();
        rdelete_label1 = new javax.swing.JLabel();
        arcombo = new javax.swing.JComboBox<String>();
        feedback_panel = new javax.swing.JPanel();
        afeedback_scroll = new javax.swing.JScrollPane();
        afeedback_table = new javax.swing.JTable();
        Fdetails_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Fdetails_textarea = new javax.swing.JTextArea();
        getfeed_button = new javax.swing.JButton();
        deletefeed_button = new javax.swing.JButton();
        fdelete_label = new javax.swing.JLabel();
        alogout_button = new javax.swing.JButton();
        reset_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("Admin");

        admin_panel.setToolTipText("");
        admin_panel.setFocusable(false);
        admin_panel.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N

        adonor_table.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        adonor_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "NID", "Blood", "Location", "Phone", "Day", "Month", "Year"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        adonor_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adonor_tableMouseClicked(evt);
            }
        });
        adonor_scroll.setViewportView(adonor_table);

        deleteuser_button.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        deleteuser_button.setText("Delete user");
        deleteuser_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteuser_buttonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel2.setText("Search by.");

        adsearch_textfield.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N

        asearch_button.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        asearch_button.setText("Search");
        asearch_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asearch_buttonActionPerformed(evt);
            }
        });

        adcombo.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        adcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID", "NID", "Phone no.", "Blood", "Location" }));
        adcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adcomboActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel4.setText("Edit Date:");

        editd_textfield.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        editd_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editd_textfieldActionPerformed(evt);
            }
        });

        editm_textfield.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        editm_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editm_textfieldActionPerformed(evt);
            }
        });

        edity_textfield.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        edity_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edity_textfieldActionPerformed(evt);
            }
        });

        Dedit_button.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        Dedit_button.setText("Edit");
        Dedit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dedit_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout donor_panelLayout = new javax.swing.GroupLayout(donor_panel);
        donor_panel.setLayout(donor_panelLayout);
        donor_panelLayout.setHorizontalGroup(
            donor_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donor_panelLayout.createSequentialGroup()
                .addComponent(adonor_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 973, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(donor_panelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(donor_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Dedit_button)
                    .addGroup(donor_panelLayout.createSequentialGroup()
                        .addGroup(donor_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(adcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(donor_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(donor_panelLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(ddelete_label, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(adsearch_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(asearch_button)
                        .addGroup(donor_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(donor_panelLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel4))
                            .addGroup(donor_panelLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(editd_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editm_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edity_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteuser_button, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        donor_panelLayout.setVerticalGroup(
            donor_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donor_panelLayout.createSequentialGroup()
                .addComponent(adonor_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(donor_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(donor_panelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(16, 16, 16)
                        .addComponent(adcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ddelete_label, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(donor_panelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(donor_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(asearch_button)
                            .addComponent(editd_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editm_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edity_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adsearch_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteuser_button, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Dedit_button))
        );

        admin_panel.addTab("Donors", donor_panel);

        arecord_table.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        arecord_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Record no.", "Name", "NID", "Phone", "Donor ID.", "Details", "Day", "Month", "Year"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        arecord_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arecord_tableMouseClicked(evt);
            }
        });
        arecord_scroll.setViewportView(arecord_table);

        deleterecord_button.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        deleterecord_button.setText("Delete rec.");
        deleterecord_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleterecord_buttonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel3.setText("Search by");

        arecord_textfield.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N

        arsearch_button.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        arsearch_button.setText("Search");
        arsearch_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arsearch_buttonActionPerformed(evt);
            }
        });

        arcombo.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        arcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Recor no.", "Patient NID" }));

        javax.swing.GroupLayout record_panelLayout = new javax.swing.GroupLayout(record_panel);
        record_panel.setLayout(record_panelLayout);
        record_panelLayout.setHorizontalGroup(
            record_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(arecord_scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 973, Short.MAX_VALUE)
            .addGroup(record_panelLayout.createSequentialGroup()
                .addGroup(record_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(record_panelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(133, 133, 133)
                        .addComponent(rdelete_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(record_panelLayout.createSequentialGroup()
                        .addComponent(arcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(arecord_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(arsearch_button)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleterecord_button, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        record_panelLayout.setVerticalGroup(
            record_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(record_panelLayout.createSequentialGroup()
                .addComponent(arecord_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(record_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleterecord_button, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(record_panelLayout.createSequentialGroup()
                        .addGroup(record_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(rdelete_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(record_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(arsearch_button)
                            .addGroup(record_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(arcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(arecord_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        admin_panel.addTab("Records", record_panel);

        afeedback_table.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        afeedback_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial no.", "Name", "NID", "Phone", "User", "Details", "Record no."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        afeedback_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                afeedback_tableMouseClicked(evt);
            }
        });
        afeedback_scroll.setViewportView(afeedback_table);

        Fdetails_label.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        Fdetails_label.setText("Details:");

        Fdetails_textarea.setColumns(20);
        Fdetails_textarea.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        Fdetails_textarea.setRows(5);
        jScrollPane1.setViewportView(Fdetails_textarea);

        getfeed_button.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getfeed_button.setText("Get feed.");
        getfeed_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getfeed_buttonActionPerformed(evt);
            }
        });

        deletefeed_button.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        deletefeed_button.setText("Delete feed.");
        deletefeed_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletefeed_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout feedback_panelLayout = new javax.swing.GroupLayout(feedback_panel);
        feedback_panel.setLayout(feedback_panelLayout);
        feedback_panelLayout.setHorizontalGroup(
            feedback_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(afeedback_scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 973, Short.MAX_VALUE)
            .addGroup(feedback_panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(feedback_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Fdetails_label)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(feedback_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, feedback_panelLayout.createSequentialGroup()
                        .addComponent(deletefeed_button, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getfeed_button, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(feedback_panelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(fdelete_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        feedback_panelLayout.setVerticalGroup(
            feedback_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(feedback_panelLayout.createSequentialGroup()
                .addComponent(afeedback_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(feedback_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(feedback_panelLayout.createSequentialGroup()
                        .addComponent(Fdetails_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, feedback_panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(fdelete_label, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(feedback_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(getfeed_button, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(deletefeed_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        admin_panel.addTab("Feedback", feedback_panel);

        alogout_button.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        alogout_button.setText("Log Out");
        alogout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alogout_buttonActionPerformed(evt);
            }
        });

        reset_button.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        reset_button.setText("Reset");
        reset_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reset_button, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alogout_button, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(admin_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(admin_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reset_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alogout_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void start()
    {
        String str1 = "Select * from Donor ";     
        DonortableInput(str1);
        String str2 = "Select * from Record ";     
        RecordtableInput(str2);
        
        
        deleterecord_button.setEnabled(false);
        deleteuser_button.setEnabled(false);
        adsearch_textfield.setText("");
        arecord_textfield.setText("");
        adcombo.setSelectedIndex(0);
        arcombo.setSelectedIndex(0);
        ddelete_label.setVisible(false);
        rdelete_label1.setVisible(false);
        jLabel4.setVisible(false);
        editd_textfield.setVisible(false);
        editm_textfield.setVisible(false);
        edity_textfield.setVisible(false);
        Dedit_button.setVisible(false);
        Fdetails_label.setVisible(false);
        fdelete_label.setVisible(false);
        Fdetails_textarea.setVisible(false);
        deletefeed_button.setVisible(false);
    }
    public void DonortableInput(String str1)
    {
        
        ResultSet rs1 =null;            
        rs1=ob.select(str1);
        
        int id;
        String name = null;
        String day = null;
        String month = null;
        String year = null;
        String blood = null;
        String phone= null;
        String nid= null;
        String location= null;
        model1= (DefaultTableModel) adonor_table.getModel();   
              
        model1.setRowCount(0);
        
        try {
                while (rs1.next())
                {
                    id=rs1.getInt("ID");
                    name=rs1.getString("D_Name");
                    day=rs1.getString("L_Day");
                    month=rs1.getString("L_Month");
                    year=rs1.getString("L_Year");
                    phone=rs1.getString("Phone");
                    blood=rs1.getString("Blood");
                    location=rs1.getString("Location");
                    nid=rs1.getString("NID");
                    
                    Object[] objs = {id,name,nid,blood,location,phone,day,month,year};
                    model1.addRow(objs);
                   
                }
            } catch (SQLException ex) {
                Logger.getLogger(Patient_interface.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
    public void RecordtableInput(String str2)
    {
        
        ResultSet rs1 =null;            
        rs1=ob.select(str2);
        
        int record;
        String name = null;
        String day = null;
        String month = null;
        String year = null;
        String did = null;
        String phone= null;
        String nid= null;
        String details= null;
        model1= (DefaultTableModel) arecord_table.getModel();   
              
        model1.setRowCount(0);
        
        try {
                while (rs1.next())
                {
                    record=rs1.getInt("ID");
                    name=rs1.getString("R_Name");
                    day=rs1.getString("R_Day");
                    month=rs1.getString("R_Month");
                    year=rs1.getString("R_Year");
                    phone=rs1.getString("Phone");
                    details=rs1.getString("Details");
                    did=rs1.getString("Donor_ID");
                    nid=rs1.getString("NID");
                    
                    
                    Object[] objs = {record,name,nid,phone,did,details,day,month,year};
                    model1.addRow(objs);
                   
                }
            } catch (SQLException ex) {
                Logger.getLogger(Patient_interface.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
    public void FeedtableInput(String str3)
    {
        
        ResultSet rs1 =null;            
        rs1=ob.select(str3);
        
        int id;
        String name = null;
        String nid = null;
        String user = null;
        String record = null;
        String details = null;
        String phone= null;
        model1= (DefaultTableModel) afeedback_table.getModel();   
              
        model1.setRowCount(0);
        
        try {
                while (rs1.next())
                {
                    id=rs1.getInt("ID");
                    name=rs1.getString("F_Name");
                    nid=rs1.getString("NID");
                    user=rs1.getString("User_type");
                    record=rs1.getString("Record_no");
                    phone=rs1.getString("Phone");
                    details=rs1.getString("Details");
                    
                    Object[] objs = {id,name,nid,phone,user,details,record};
                    model1.addRow(objs);
                   
                }
            } catch (SQLException ex) {
                Logger.getLogger(Patient_interface.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    private void alogout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alogout_buttonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Main_interface().setVisible(true);
    }//GEN-LAST:event_alogout_buttonActionPerformed

    private void adonor_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adonor_tableMouseClicked
        // TODO add your handling code here:
        int index = adonor_table.getSelectedRow();
        String ID= model1.getValueAt(index, 0).toString();
        String Day= model1.getValueAt(index, 6).toString();
        String Month= model1.getValueAt(index, 7).toString();
        String Year= model1.getValueAt(index, 8).toString();
        
        ddelete_label.setText(ID);
        editd_textfield.setText(Day);
        editm_textfield.setText(Month);
        edity_textfield.setText(Year);
    }//GEN-LAST:event_adonor_tableMouseClicked

    private void arecord_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arecord_tableMouseClicked
        // TODO add your handling code here:
        int index = arecord_table.getSelectedRow();
        String ID= model1.getValueAt(index, 0).toString();
        
        rdelete_label1.setText(ID);
    }//GEN-LAST:event_arecord_tableMouseClicked

    private void afeedback_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_afeedback_tableMouseClicked
        // TODO add your handling code here:
        int index = afeedback_table.getSelectedRow();
        String ID= model1.getValueAt(index, 0).toString();
        String details= model1.getValueAt(index, 5).toString();
        
        fdelete_label.setText(ID);
        Fdetails_textarea.setText(details);
        
    }//GEN-LAST:event_afeedback_tableMouseClicked

    private void asearch_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asearch_buttonActionPerformed
        // TODO add your handling code here:
        int c= adcombo.getSelectedIndex();
        String selected= adsearch_textfield.getText();
        
        deleteuser_button.setEnabled(true);
        jLabel4.setVisible(true);
        editd_textfield.setVisible(true);
        editm_textfield.setVisible(true);
        edity_textfield.setVisible(true);
        Dedit_button.setVisible(true);
        
        if (c==0)
        {
            String str = "Select * from Donor where ID = '"+selected+"'";     
            DonortableInput(str);  
        }
        
        else if (c==1)
        {
            String str = "Select * from Donor where NID = '"+selected+"'";     
            DonortableInput(str);  
        }
        
        else if (c==2)
        {
            String str = "Select * from Donor where Phone = '"+selected+"'";     
            DonortableInput(str);  
        }
        
        
        else if (c==3)
        {
            String str = "Select * from Donor where Blood = '"+selected+"'";     
            DonortableInput(str);  
        }
        
        else if (c==4)
        {
            String str = "Select * from Donor where Location = '"+selected+"'";     
            DonortableInput(str);  
        }
    }//GEN-LAST:event_asearch_buttonActionPerformed

    private void reset_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_buttonActionPerformed
        // TODO add your handling code here:
        start();
    }//GEN-LAST:event_reset_buttonActionPerformed

    private void arsearch_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arsearch_buttonActionPerformed
        // TODO add your handling code here:
        
        int c= arcombo.getSelectedIndex();
        String selected= arecord_textfield.getText();
        
        deleterecord_button.setEnabled(true);
        
        if (c==0)
        {
            String str = "Select * from Record where ID = '"+selected+"'";     
            RecordtableInput(str);  
        }
        
        else if (c==1)
        {
            String str = "Select * from Record where NID = '"+selected+"'";     
            RecordtableInput(str);  
        }
    }//GEN-LAST:event_arsearch_buttonActionPerformed

    private void deleteuser_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteuser_buttonActionPerformed
        // TODO add your handling code here:
        String str;
        str = "delete from Donor where ID= '"+ddelete_label.getText()+"'";
        ob.delete(str);
        JOptionPane.showMessageDialog(null,"User Deleted","Success",JOptionPane.INFORMATION_MESSAGE);
        start();
    }//GEN-LAST:event_deleteuser_buttonActionPerformed

    private void deleterecord_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleterecord_buttonActionPerformed
        // TODO add your handling code here:
        String str;
        str = "delete from Record where ID= '"+rdelete_label1.getText()+"'";
        ob.delete(str);
        JOptionPane.showMessageDialog(null,"Record Deleted","Success",JOptionPane.INFORMATION_MESSAGE);
        start();
    }//GEN-LAST:event_deleterecord_buttonActionPerformed

    private void editd_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editd_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editd_textfieldActionPerformed

    private void editm_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editm_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editm_textfieldActionPerformed

    private void edity_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edity_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edity_textfieldActionPerformed

    private void Dedit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dedit_buttonActionPerformed
        // TODO add your handling code here:
        String str2;
        str2 = "update Donor set L_Day = '" + editd_textfield.getText()+ "',L_Month = '" + editm_textfield.getText()+ "',L_Year = '" + edity_textfield.getText()+ "' where ID='"+ddelete_label.getText()+"'";
                    ob.update(str2);
                    JOptionPane.showMessageDialog(null, "Edited and Saved", "Success", JOptionPane.INFORMATION_MESSAGE);
                    start();
    }//GEN-LAST:event_Dedit_buttonActionPerformed

    private void getfeed_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getfeed_buttonActionPerformed
        // TODO add your handling code here:
        String str3 = "Select * from Feedback ";     
        FeedtableInput(str3);
        
        Fdetails_label.setVisible(true);
        Fdetails_textarea.setVisible(true);
        deletefeed_button.setVisible(true);
    }//GEN-LAST:event_getfeed_buttonActionPerformed

    private void deletefeed_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletefeed_buttonActionPerformed
        // TODO add your handling code here:
        String str;
        str = "delete from Feedback where ID= '"+fdelete_label.getText()+"'";
        ob.delete(str);
        JOptionPane.showMessageDialog(null,"Feedback Deleted","Success",JOptionPane.INFORMATION_MESSAGE);
        
        Fdetails_textarea.setText("");
        
        String str1;
        str1= "Select * from Feedback ";
        FeedtableInput(str1);
    }//GEN-LAST:event_deletefeed_buttonActionPerformed

    private void adcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adcomboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dedit_button;
    private javax.swing.JLabel Fdetails_label;
    private javax.swing.JTextArea Fdetails_textarea;
    private javax.swing.JComboBox<String> adcombo;
    private javax.swing.JTabbedPane admin_panel;
    private javax.swing.JScrollPane adonor_scroll;
    private javax.swing.JTable adonor_table;
    private javax.swing.JTextField adsearch_textfield;
    private javax.swing.JScrollPane afeedback_scroll;
    private javax.swing.JTable afeedback_table;
    private javax.swing.JButton alogout_button;
    private javax.swing.JComboBox<String> arcombo;
    private javax.swing.JScrollPane arecord_scroll;
    private javax.swing.JTable arecord_table;
    private javax.swing.JTextField arecord_textfield;
    private javax.swing.JButton arsearch_button;
    private javax.swing.JButton asearch_button;
    private javax.swing.JLabel ddelete_label;
    private javax.swing.JButton deletefeed_button;
    private javax.swing.JButton deleterecord_button;
    private javax.swing.JButton deleteuser_button;
    private javax.swing.JPanel donor_panel;
    private javax.swing.JTextField editd_textfield;
    private javax.swing.JTextField editm_textfield;
    private javax.swing.JTextField edity_textfield;
    private javax.swing.JLabel fdelete_label;
    private javax.swing.JPanel feedback_panel;
    private javax.swing.JButton getfeed_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rdelete_label1;
    private javax.swing.JPanel record_panel;
    private javax.swing.JButton reset_button;
    // End of variables declaration//GEN-END:variables
}
