/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bloodman;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Turbo
 */
public class Donor_login extends javax.swing.JFrame {

    /**
     * Creates new form Donor_login
     */
    Database ob;
    public Donor_login() {
        initComponents();
        this.setLocationRelativeTo(null);
        ob= new Database();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpass_passfield = new javax.swing.JPasswordField();
        dlogin_button = new javax.swing.JButton();
        dback_button = new javax.swing.JButton();
        Login_lebel = new javax.swing.JLabel();
        user_label = new javax.swing.JLabel();
        pass_label = new javax.swing.JLabel();
        dnid_textfield = new javax.swing.JTextField();
        creatacc_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dpass_passfield.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        dpass_passfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpass_passfieldActionPerformed(evt);
            }
        });

        dlogin_button.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        dlogin_button.setText("Log in");
        dlogin_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlogin_buttonActionPerformed(evt);
            }
        });

        dback_button.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        dback_button.setText("Back");
        dback_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dback_buttonActionPerformed(evt);
            }
        });

        Login_lebel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        Login_lebel.setText("Donor Login");

        user_label.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        user_label.setText("NID :");

        pass_label.setFont(new java.awt.Font("Times New Roman", 0, 21)); // NOI18N
        pass_label.setText("Password :");

        dnid_textfield.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        dnid_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dnid_textfieldActionPerformed(evt);
            }
        });

        creatacc_button.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        creatacc_button.setText("Create Account");
        creatacc_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creatacc_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Login_lebel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(user_label, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dnid_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pass_label, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(creatacc_button, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dlogin_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dback_button))
                            .addComponent(dpass_passfield))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Login_lebel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_label, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dnid_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dpass_passfield, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlogin_button)
                    .addComponent(dback_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(creatacc_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dpass_passfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpass_passfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpass_passfieldActionPerformed

    private void dnid_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dnid_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dnid_textfieldActionPerformed

    private void dback_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dback_buttonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Main_interface().setVisible(true);
    }//GEN-LAST:event_dback_buttonActionPerformed

    private void creatacc_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creatacc_buttonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Donor_Registration().setVisible(true);
    }//GEN-LAST:event_creatacc_buttonActionPerformed

    private void dlogin_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlogin_buttonActionPerformed
        // TODO add your handling code here:
        String msg = dnid_textfield.getText();
        
        ResultSet rs =null;
        String str = "Select * from Donor where NID='"+dnid_textfield.getText()+"' and Password='"+dpass_passfield.getText()+"'";
        rs=ob.select(str);
        try {
            if (rs.next()) {
                this.dispose();
                new Donor_interface(msg).setVisible(true);
                
            }
            else
            {
                 JOptionPane.showMessageDialog(null,"Incorrect NID or Password","Error",JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Donor_Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dlogin_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Donor_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Donor_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Donor_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Donor_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Donor_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Login_lebel;
    private javax.swing.JButton creatacc_button;
    private javax.swing.JButton dback_button;
    private javax.swing.JButton dlogin_button;
    private javax.swing.JTextField dnid_textfield;
    private javax.swing.JPasswordField dpass_passfield;
    private javax.swing.JLabel pass_label;
    private javax.swing.JLabel user_label;
    // End of variables declaration//GEN-END:variables
}
