/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bloodman;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Turbo
 */
public class Donor_Registration extends javax.swing.JFrame {

    /**
     * Creates new form Donor_Registration
     */
    Database ob;
    public Donor_Registration() {
        initComponents();
        this.setLocationRelativeTo(null);
         ob = new Database();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        name_textfield = new javax.swing.JTextField();
        nid_textfield = new javax.swing.JTextField();
        phone_textfield = new javax.swing.JTextField();
        blood_combo = new javax.swing.JComboBox<String>();
        location_combo = new javax.swing.JComboBox<String>();
        pass_passfield = new javax.swing.JPasswordField();
        repass_passfield = new javax.swing.JPasswordField();
        singup_button = new javax.swing.JButton();
        back_button = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        reset_button = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Day_textfield = new javax.swing.JTextField();
        month_textfield = new javax.swing.JTextField();
        year_textfield = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("Registration");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("*Please fill up all of the following Informations.");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Name:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("NID:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Phone No. ");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText("Blood Type:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setText("Location:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel9.setText("Password:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel10.setText("Re-Type Pass:");

        name_textfield.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N

        nid_textfield.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        nid_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nid_textfieldActionPerformed(evt);
            }
        });
        nid_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nid_textfieldKeyTyped(evt);
            }
        });

        phone_textfield.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        phone_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_textfieldActionPerformed(evt);
            }
        });
        phone_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phone_textfieldKeyTyped(evt);
            }
        });

        blood_combo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        blood_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));

        location_combo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        location_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dhaka", "Rajshahi", "Chittagong", "Barisal", "Khulna", "Mymensingh", "Sylhet", "Rangpur" }));

        pass_passfield.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        pass_passfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_passfieldActionPerformed(evt);
            }
        });

        repass_passfield.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N

        singup_button.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        singup_button.setText("Sing up");
        singup_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singup_buttonActionPerformed(evt);
            }
        });

        back_button.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        back_button.setText("Back");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setText("Last Donation:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel12.setText("(Put the date of 120 days before if never donated before)");

        reset_button.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        reset_button.setText("Reset");
        reset_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_buttonActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel13.setText("Day");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel11.setText("Month");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel14.setText("Year");

        Day_textfield.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Day_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Day_textfieldActionPerformed(evt);
            }
        });
        Day_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Day_textfieldKeyTyped(evt);
            }
        });

        month_textfield.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        month_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                month_textfieldActionPerformed(evt);
            }
        });
        month_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                month_textfieldKeyTyped(evt);
            }
        });

        year_textfield.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        year_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year_textfieldActionPerformed(evt);
            }
        });
        year_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                year_textfieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(singup_button, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reset_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Day_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(month_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(year_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(phone_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(blood_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pass_passfield, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(location_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(repass_passfield, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(nid_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nid_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blood_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(location_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pass_passfield, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(repass_passfield, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(month_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Day_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(back_button, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(reset_button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(singup_button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nid_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nid_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nid_textfieldActionPerformed

    private void pass_passfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_passfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_passfieldActionPerformed

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Donor_login().setVisible(true);
    }//GEN-LAST:event_back_buttonActionPerformed

    private void nid_textfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nid_textfieldKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
        
        boolean max = nid_textfield.getText().length() > 7;
        if ( max ){
        evt.consume();
        }
    }//GEN-LAST:event_nid_textfieldKeyTyped

    private void phone_textfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phone_textfieldKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
        
        boolean max = phone_textfield.getText().length() > 10;
        if ( max ){
        evt.consume();
        } 
        
    }//GEN-LAST:event_phone_textfieldKeyTyped

    private void phone_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_textfieldActionPerformed

    private void singup_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singup_buttonActionPerformed
        // TODO add your handling code here:
        int c;
        c= checkInput();
        
        String Inputname= name_textfield.getText();
        String Inputphone= phone_textfield.getText();
        String Inputnid= nid_textfield.getText();
        String Inputpass= pass_passfield.getText();
        String Inputday= Day_textfield.getText();
        String Inputmonth= month_textfield.getText();
        String Inputyear= year_textfield.getText();
        String Inputblood= blood_combo.getSelectedItem().toString();
        String Inputlocation= location_combo.getSelectedItem().toString();
        String InputAvail= "Yes";
        
        if (c==1)
        {
            ResultSet rs =null;
            String str = "Select * from Donor where NID='"+nid_textfield.getText()+"' or Phone='"+phone_textfield.getText()+"'";
            rs=ob.select(str);
            try {
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null,"NID or Phone no. already exits","Error",JOptionPane.ERROR_MESSAGE);//   jodi value alrready thakle tokon
                }
                else
                {
                    String sql = "insert into Donor (D_Name,NID,Blood,Location,Phone,Password,Availability,L_Day,L_Month,L_Year) values('"+Inputname+"','"+Inputnid+"','"+Inputblood+"','"+Inputlocation+"','"+Inputphone+"','"+Inputpass+"','"+InputAvail+"','"+Inputday+"','"+Inputmonth+"','"+Inputyear+"')";
                    ob.insert(sql);
                    JOptionPane.showMessageDialog(null,"Account created\n"+"Please remember these terms and conditions:\n"+"*Must be a regular blood donator.\n"+"*If no blood donation activity in 200 days after last blood donation\n"+" your account will be deleted\n"+"*Any proven foul play will result in account deletion.\n"+"*Always check your account after donation cofirmation to see added record.\n"+"*Set your Availability to yes after 120 days after blood donation.","Success",JOptionPane.INFORMATION_MESSAGE);
                    clear();
                }
        } catch (SQLException ex) {
            Logger.getLogger(Donor_Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        }
             
        
        else
        {
            JOptionPane.showMessageDialog(null,"Invalid Input or Password don't match","Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_singup_buttonActionPerformed

   
    private void reset_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_buttonActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_reset_buttonActionPerformed

    private void Day_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Day_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Day_textfieldActionPerformed

    private void month_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_month_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_month_textfieldActionPerformed

    private void year_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_year_textfieldActionPerformed

    private void Day_textfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Day_textfieldKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
        
       
    }//GEN-LAST:event_Day_textfieldKeyTyped

    private void month_textfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_month_textfieldKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
            
        }
        
        
      
    }//GEN-LAST:event_month_textfieldKeyTyped

    private void year_textfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_year_textfieldKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
       
    }//GEN-LAST:event_year_textfieldKeyTyped

    public void clear()
    {
        name_textfield.setText("");
        phone_textfield.setText("");
        nid_textfield.setText("");
        pass_passfield.setText("");
        repass_passfield.setText("");
        Day_textfield.setText("");
        month_textfield.setText("");
        year_textfield.setText("");
        blood_combo.setSelectedIndex(0);
        location_combo.setSelectedIndex(0);
    }
    
    public int checkInput()
    {
        String pass1,pass;
        
        pass= pass_passfield.getText();
        pass1= repass_passfield.getText();
        if(!nid_textfield.getText().isEmpty() || !name_textfield.getText().isEmpty() || !pass_passfield.getText().isEmpty() || !repass_passfield.getText().isEmpty()  || !phone_textfield.getText().isEmpty()  || !Day_textfield.getText().isEmpty()  || !month_textfield.getText().isEmpty()  || !year_textfield.getText().isEmpty()) 
        {
            if( pass.equals(pass1))
            {
                return 1;
            }
            else
            {
                return 0;
            }
            
        }
        else 
        {
            return 0;
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Donor_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Donor_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Donor_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Donor_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Donor_Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Day_textfield;
    private javax.swing.JButton back_button;
    private javax.swing.JComboBox<String> blood_combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> location_combo;
    private javax.swing.JTextField month_textfield;
    private javax.swing.JTextField name_textfield;
    private javax.swing.JTextField nid_textfield;
    private javax.swing.JPasswordField pass_passfield;
    private javax.swing.JTextField phone_textfield;
    private javax.swing.JPasswordField repass_passfield;
    private javax.swing.JButton reset_button;
    private javax.swing.JButton singup_button;
    private javax.swing.JTextField year_textfield;
    // End of variables declaration//GEN-END:variables
}
