/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bloodman;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Turbo
 */
public class Feedback_interface extends javax.swing.JFrame {

    /**
     * Creates new form Feedback_interface
     */
    Database ob1= new Database();
    public Feedback_interface() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    
    public void clear()
    {
        fname_textfield.setText("");
        fdetails_textarea.setText("");
        fnid_textfield.setText("");
        fphone_textfield.setText("");
        frecord_textfield.setText("");
        from_combo.setSelectedIndex(0);
    }
    
    public int checkInput()
    {
        if(!fname_textfield.getText().isEmpty() || !fnid_textfield.getText().isEmpty() || !fphone_textfield.getText().isEmpty() || !fdetails_textarea.getText().isEmpty()  || !frecord_textfield.getText().isEmpty()) 
        {
            return 1;
        }
        else 
        {
            return 0;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        from_combo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        fname_textfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fphone_textfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fnid_textfield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fdetails_textarea = new javax.swing.JTextArea();
        fsubmit_button = new javax.swing.JButton();
        fback_button = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        frecord_textfield = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("Feedback");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel2.setText("From:");

        from_combo.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        from_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Patient", "Donor" }));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel3.setText("*Name:");

        fname_textfield.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        fname_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fname_textfieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel4.setText("*Phone no.");

        fphone_textfield.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        fphone_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fphone_textfieldActionPerformed(evt);
            }
        });
        fphone_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fphone_textfieldKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel5.setText("*NID:");

        fnid_textfield.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        fnid_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fnid_textfieldKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel6.setText("Complain on:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel9.setText("*Details:");

        fdetails_textarea.setColumns(20);
        fdetails_textarea.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        fdetails_textarea.setRows(5);
        jScrollPane1.setViewportView(fdetails_textarea);

        fsubmit_button.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        fsubmit_button.setText("Submit");
        fsubmit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fsubmit_buttonActionPerformed(evt);
            }
        });

        fback_button.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        fback_button.setText("Back");
        fback_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fback_buttonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel10.setText("Rec. no.");

        frecord_textfield.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        frecord_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frecord_textfieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel7.setText("(If you don't know put N/A)");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Please put their the name and Phone no. in details");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("If you have a complain against someone");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(fback_button)
                                .addGap(8, 8, 8)
                                .addComponent(fsubmit_button))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(from_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fphone_textfield)
                                    .addComponent(fname_textfield)
                                    .addComponent(fnid_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)))
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addComponent(frecord_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(from_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fname_textfield))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fphone_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fnid_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frecord_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(4, 4, 4)
                .addComponent(jLabel8)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fback_button)
                    .addComponent(fsubmit_button))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fname_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fname_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fname_textfieldActionPerformed

    private void fphone_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fphone_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fphone_textfieldActionPerformed

    private void fback_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fback_buttonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Main_interface().setVisible(true);
    }//GEN-LAST:event_fback_buttonActionPerformed

    private void frecord_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frecord_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frecord_textfieldActionPerformed

    private void fphone_textfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fphone_textfieldKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
        
        boolean max = fphone_textfield.getText().length() > 10;
        if ( max ){
        evt.consume();
        }
    }//GEN-LAST:event_fphone_textfieldKeyTyped

    private void fnid_textfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnid_textfieldKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
        
        boolean max = fnid_textfield.getText().length() > 7;
        if ( max ){
        evt.consume();
        }
    }//GEN-LAST:event_fnid_textfieldKeyTyped

    private void fsubmit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fsubmit_buttonActionPerformed
        // TODO add your handling code here:
        
        int c;
        c= checkInput();
        
        String Inputname= fname_textfield.getText();
        String Inputphone= fphone_textfield.getText();
        String Inputnid= fnid_textfield.getText();
        String Inputrec= frecord_textfield.getText();
        String Inputdetails= fdetails_textarea.getText();
        String Inputfrom= from_combo.getSelectedItem().toString();
        
        
        if (c==1)
        {
            String sql = "insert into Feedback (Record_no,F_Name,Phone,NID,User_type,Details) values('"+Inputrec+"','"+Inputname+"','"+Inputphone+"','"+Inputnid+"','"+Inputfrom+"','"+Inputdetails+"')";
            ob1.insert(sql);
            JOptionPane.showMessageDialog(null,"Feedback submitted","Success",JOptionPane.INFORMATION_MESSAGE);
            clear();  
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please fill the information","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_fsubmit_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Feedback_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Feedback_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Feedback_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Feedback_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Feedback_interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fback_button;
    private javax.swing.JTextArea fdetails_textarea;
    private javax.swing.JTextField fname_textfield;
    private javax.swing.JTextField fnid_textfield;
    private javax.swing.JTextField fphone_textfield;
    private javax.swing.JTextField frecord_textfield;
    private javax.swing.JComboBox<String> from_combo;
    private javax.swing.JButton fsubmit_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
