/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bloodman;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Turbo
 */
public class Patient_interface extends javax.swing.JFrame {

    /**
     * Creates new form Patient_interface
     */
    
    Calendar calenda= new GregorianCalendar();
 
    int day = calenda.get(Calendar.DAY_OF_MONTH);
    int month = calenda.get(Calendar.MONTH);
    int year = calenda.get(Calendar.YEAR);
    
    Database ob= new Database();
    String str1 = "Select * from Donor";
    DefaultTableModel model1;
    
    public Patient_interface() {
        initComponents();
        this.setLocationRelativeTo(null);
        start();
    }
    
    public void tableInput(String str1)
    {
        
        ResultSet rs1 =null;            
        rs1=ob.select(str1);
        
        int id;
        String name = null;
        model1= (DefaultTableModel) pdonor_table.getModel();   
              
        model1.setRowCount(0);
        
        try {
                while (rs1.next())
                {
                    id=rs1.getInt("ID");
                    name=rs1.getString("D_Name");
                    
                    Object[] objs = {id,name};
                    model1.addRow(objs);
                   
                }
            } catch (SQLException ex) {
                Logger.getLogger(Patient_interface.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    public void start()
    {
        pgetinfo_button.setEnabled(false);
        pyes_button.setEnabled(false);
        pno_button.setEnabled(false);
        pname_label.setVisible(false);
        pid_label.setVisible(false);
        pphone_label.setVisible(false);
    }
    public void clear()
    {
        pname_textfield.setText("");
        pphone_textfield.setText("");
        pnid_textfield.setText("");
        pdetails_textarea.setText("");
        pblood_combo.setSelectedIndex(0);
        plocation_combo.setSelectedIndex(0);
        
        pname_textfield.setEnabled(true);
        pphone_textfield.setEnabled(true);
        pnid_textfield.setEnabled(true);
        pdetails_textarea.setEnabled(true);
        pblood_combo.setEnabled(true);
        plocation_combo.setEnabled(true);
    }
    
    public void off()
    {
        pname_textfield.setEnabled(false);
        pphone_textfield.setEnabled(false);
        pnid_textfield.setEnabled(false);
        pdetails_textarea.setEnabled(false);
        pblood_combo.setEnabled(false);
        plocation_combo.setEnabled(false);
    }
    
    public int checkInput()
    {
        if(!pname_textfield.getText().isEmpty() || !pnid_textfield.getText().isEmpty() || !pphone_textfield.getText().isEmpty() || !pdetails_textarea.getText().isEmpty()) 
        {
            return 1;
        }
        else 
        {
            return 0;
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pname_textfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pphone_textfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pnid_textfield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pblood_combo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        plocation_combo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        psearch_button = new javax.swing.JButton();
        pback_button = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pdonor_table = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pdetails_textarea = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        pgetinfo_button = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        pyes_button = new javax.swing.JButton();
        pno_button = new javax.swing.JButton();
        preset_button = new javax.swing.JButton();
        pname_label = new javax.swing.JLabel();
        pphone_label = new javax.swing.JLabel();
        pid_label = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jLabel12.setText("jLabel12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("Search Donor");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setText("Your info:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel3.setText("*Name:");

        pname_textfield.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel4.setText("*Phone no.");

        pphone_textfield.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        pphone_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pphone_textfieldActionPerformed(evt);
            }
        });
        pphone_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pphone_textfieldKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel5.setText("*NID:");

        pnid_textfield.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        pnid_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pnid_textfieldKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel6.setText("Patient:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel7.setText("Blood Type:");

        pblood_combo.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        pblood_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel8.setText("Location:");

        plocation_combo.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        plocation_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dhaka", "Rajshahi", "Chittagong", "Barisal", "Khulna", "Mymensingh", "Sylhet", "Rangpur" }));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel9.setText("Patient Details:");

        psearch_button.setFont(new java.awt.Font("Times New Roman", 0, 32)); // NOI18N
        psearch_button.setText("Search");
        psearch_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psearch_buttonActionPerformed(evt);
            }
        });

        pback_button.setFont(new java.awt.Font("Times New Roman", 0, 32)); // NOI18N
        pback_button.setText("Back");
        pback_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pback_buttonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel10.setText("Donor info:");

        jScrollPane1.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N

        pdonor_table.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        pdonor_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User_ID", "Name"
            }
        ));
        pdonor_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pdonor_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(pdonor_table);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel11.setText("Name:");

        pdetails_textarea.setColumns(20);
        pdetails_textarea.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        pdetails_textarea.setRows(5);
        jScrollPane2.setViewportView(pdetails_textarea);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel13.setText("Phone no.");

        pgetinfo_button.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        pgetinfo_button.setText("Get info");
        pgetinfo_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pgetinfo_buttonActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel14.setText("Donation Confirmation:");

        pyes_button.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        pyes_button.setText("Yes");
        pyes_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pyes_buttonActionPerformed(evt);
            }
        });

        pno_button.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        pno_button.setText("No");
        pno_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pno_buttonActionPerformed(evt);
            }
        });

        preset_button.setFont(new java.awt.Font("Times New Roman", 0, 32)); // NOI18N
        preset_button.setText("Reset");
        preset_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preset_buttonActionPerformed(evt);
            }
        });

        pname_label.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N

        pphone_label.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel15.setText("Please select a Donor and click Get info");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(6, 6, 6)
                                .addComponent(pname_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(jLabel4)
                                .addGap(6, 6, 6)
                                .addComponent(pphone_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(pnid_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(6, 6, 6)
                                .addComponent(pblood_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(jLabel8)
                                .addGap(6, 6, 6)
                                .addComponent(plocation_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel15))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pid_label, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120)
                                .addComponent(pgetinfo_button))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(44, 44, 44)
                                .addComponent(pname_label, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(pphone_label, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(preset_button, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(pback_button, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(psearch_button, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(pyes_button, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(pno_button, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pname_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pphone_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel5))
                            .addComponent(pnid_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(jLabel6)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pblood_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plocation_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))))
                        .addGap(9, 9, 9)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pid_label, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pgetinfo_button))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pname_label, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(pphone_label, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(jLabel14)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(preset_button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pback_button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(psearch_button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pyes_button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pno_button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pphone_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pphone_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pphone_textfieldActionPerformed

    private void pyes_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pyes_buttonActionPerformed
        // TODO add your handling code here:
        int c;
        c= checkInput();
        
        int inputDay;
        int inputMonth;
        int inputYear;
        
        inputDay = day;
        inputMonth = month+1;
        inputYear = year;
        String Inputname= pname_textfield.getText();
        String Inputphone= pphone_textfield.getText();
        String Inputnid= pnid_textfield.getText();
        String Inputdid= pid_label.getText();
        String Inputdetails= pdetails_textarea.getText();
        String Inputavail= "No";
        
            String sql = "insert into Record (R_Name,NID,Phone,Donor_ID,Details,R_Day,R_Month,R_Year) values('"+Inputname+"','"+Inputnid+"','"+Inputphone+"','"+Inputdid+"','"+Inputdetails+"','"+inputDay+"','"+inputMonth+"','"+inputYear+"')";
            ob.insert(sql);
            JOptionPane.showMessageDialog(null,"Thank you"+"\n*Please give your feedback if any problem occurs.",null,JOptionPane.INFORMATION_MESSAGE);
            
            String str;
            str = "update Donor set L_Day = '" + inputDay + "',L_Month = '" + inputMonth + "',L_Year = '" + inputYear + "',Availability = '" + Inputavail + "' where ID='"+pid_label.getText()+"'";
            ob.update(str);
        
            this.dispose();
            new Main_interface().setVisible(true);
       
    }//GEN-LAST:event_pyes_buttonActionPerformed

    private void pno_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pno_buttonActionPerformed
        // TODO add your handling code here:
        pgetinfo_button.setEnabled(true);
        pdonor_table.setEnabled(true);
        pyes_button.setEnabled(false);
        pno_button.setEnabled(false);
        pname_label.setVisible(false);
        pphone_label.setVisible(false);
        pback_button.setEnabled(true);
    }//GEN-LAST:event_pno_buttonActionPerformed

    private void pback_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pback_buttonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Main_interface().setVisible(true);
    }//GEN-LAST:event_pback_buttonActionPerformed

    private void pnid_textfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnid_textfieldKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
        
        boolean max = pnid_textfield.getText().length() > 7;
        if ( max ){
        evt.consume();
        }
    }//GEN-LAST:event_pnid_textfieldKeyTyped

    private void pphone_textfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pphone_textfieldKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
        
        boolean max = pphone_textfield.getText().length() > 10;
        if ( max ){
        evt.consume();
        }
    }//GEN-LAST:event_pphone_textfieldKeyTyped

    private void preset_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preset_buttonActionPerformed
        // TODO add your handling code here:
        clear();
        pgetinfo_button.setEnabled(false);
    }//GEN-LAST:event_preset_buttonActionPerformed

    private void psearch_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psearch_buttonActionPerformed
        // TODO add your handling code here:
        String selectedblood=(String) pblood_combo.getSelectedItem();
        String selectedlocation = (String) plocation_combo.getSelectedItem();
        String selectedAvailability= "Yes";
        
        int c;
        c=checkInput();
        
        if (c==1)
        {
            String str = "Select * from Donor where Blood = '"+selectedblood+"'and Location = '"+selectedlocation+"' and Availability = '"+selectedAvailability+"'";     
            tableInput(str);
            pgetinfo_button.setEnabled(true);
            off();
            
            JOptionPane.showMessageDialog(null,"Please click reset now if you have put worng info",null,JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Invalid Input","Error",JOptionPane.ERROR_MESSAGE);
        }
        
            
        
        
    }//GEN-LAST:event_psearch_buttonActionPerformed

    public void phone()
    {
        ResultSet rs =null;
        String str = "Select * from Donor where ID ='"+pid_label.getText()+"'";
        rs=ob.select(str);
        try {
            while (rs.next()) {
                pphone_label.setText(rs.getString("Phone"));             
            }
        } catch (SQLException ex) {
            Logger.getLogger(Donor_interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void pdonor_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pdonor_tableMouseClicked
        // TODO add your handling code here:
        int index = pdonor_table.getSelectedRow();
        String ID= model1.getValueAt(index, 0).toString();
        String name= model1.getValueAt(index, 1).toString();
        
        pid_label.setText(ID);
        pname_label.setText(name);
        phone();
    }//GEN-LAST:event_pdonor_tableMouseClicked

    private void pgetinfo_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pgetinfo_buttonActionPerformed
        // TODO add your handling code here:
        preset_button.setEnabled(false);
        psearch_button.setEnabled(false);
        pback_button.setEnabled(false);
        pdonor_table.setEnabled(false);
        pname_label.setVisible(true);
        pphone_label.setVisible(true);
        pyes_button.setEnabled(true);
        pno_button.setEnabled(true);
        pgetinfo_button.setEnabled(false);
        
        
        
    }//GEN-LAST:event_pgetinfo_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patient_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patient_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patient_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patient_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patient_interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton pback_button;
    private javax.swing.JComboBox<String> pblood_combo;
    private javax.swing.JTextArea pdetails_textarea;
    private javax.swing.JTable pdonor_table;
    private javax.swing.JButton pgetinfo_button;
    private javax.swing.JLabel pid_label;
    private javax.swing.JComboBox<String> plocation_combo;
    private javax.swing.JLabel pname_label;
    private javax.swing.JTextField pname_textfield;
    private javax.swing.JTextField pnid_textfield;
    private javax.swing.JButton pno_button;
    private javax.swing.JLabel pphone_label;
    private javax.swing.JTextField pphone_textfield;
    private javax.swing.JButton preset_button;
    private javax.swing.JButton psearch_button;
    private javax.swing.JButton pyes_button;
    // End of variables declaration//GEN-END:variables
}
